import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Content from './components/Content'
import Header from './components/Header'
import LefttNavBar from './components/LefttNavBar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
       <div >
      <LefttNavBar />
      <Header />
      <Content />
       </div>

    </div>
  )
}
